routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Usando controladores
//Route::get('/', 'PagesController@home')->name('home')->middleware('example'); //Middleware

Route::get('/', 'PagesController@home')->name('home');

/*Route::get('contactos', 'PagesController@contactos')->name('contactos');

Route::post('contacto', 'PagesController@mensaje');

Route::get('contactame',[
    'as' => 'contactactamee', 
    'uses'=>'PagesController@contact'
    ]); //Otra forma de darle un Alias a un Controlador
*/

Route::get('saludos/{nombre?}', 'PagesController@saludos') //parametro opcional
                                ->name('saludos')
                                ->where('nombre', "[A-Za-z]+");


//USO de REST
/*Route::get('mensajes','MessagesController@index')->name('messages.index');
Route::get('mensajes/create','MessagesController@create')->name('messages.create');
Route::post('mensajes','MessagesController@store')->name('messages.store');
Route::get('mensajes/{id}','MessagesController@show')->name('messages.show');
Route::get('mensajes/{id}/edit','MessagesController@edit')->name('messages.edit');
Route::put('mensajes/{id}','MessagesController@update')->name('messages.update');
Route::delete('mensajes/{id}','MessagesController@destroy')->name('messages.destroy');*/




    //Ruta para crear un usuario de prueba

/*Route::get('test',function(){
    $user = new App\User;

    $user->name = 'Estudiante';
    $user->email = 'jorge3@gmail.com';
    $user->password = bcrypt('123123'); //Encriptamos la contraseña

    $user->save();

    return $user;

    $rol = new \App\Role;
    $rol->create([
        "nombre" => "admin",
        "description" => "Este rol tiene permisos de Administrador",
        "display_name" => "Administrador del sitio"
    ]);
    $rol2 = new \App\Role;
    $rol2->create([
        "nombre" => "mod",
        "description" => "Este rol tiene permisos de Moderador",
        "display_name" => "Moderador de comentarios"
    ]);

});*/

DB::listen(function($query){
    echo "<pre>{ $query->sql}</pre>";
});

Route::get('roles', function(){
    return \App\Role::with('user')->get();
});

//Reduciendo las rutas a una sola linea
Route::resource('mensajes','MessagesController');
Route::resource('usuarios','UsersController');


//Autenticacion

Route::get('login','Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout');
 

resources/views/contactos.blade.php
    @extends('layout')

    @section('content')
        <h1>CONTACTOS</h1>
        <h2>Escribenos</h2>
        @if(session()->has('keyMensaje'))
        
            <h3>{{ session('keyMensaje')}}</h3>
        
        @else
        <form action="contacto" method="post">
            <p><label for="nombre">
                Nombre:
                <input type="text" name="nombre" value="{{ old('nombre') }}">
                {!! $errors->first('nombre','<span class="error">:message</span>') !!}
            </label></p>
            <p><label for="email">
                Email:
                <input type="text" name="email" value="{{old('email')}}">
                {!! $errors->first('email','<span class="error">:message</span>') !!}
            </label></p>
            <p><label for="mensaje">
                Mensaje:
                <textarea name="mensaje"> {{old('mensaje')}}</textarea>
                {!! $errors->first('mensaje','<span class="error">:message</span>') !!}
            </label></p>
            
            <input type="submit" value="Enviar">
        </form>
        <hr>
        @endif
        
    @stop

resources/views/home.blade.php
@extends('layout')

@section('content')
    <h1>HOME</h1>
@stop

resources/views/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Mi sitio</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="/css/app.css">
    
</head>
<body>
    <header>
        <!--<h1>{{ request()->url()  }}</h1>
        <h2>{{ request()->is('/') ? 'Estas en el Home' : 'No estas en el home' }}</h2>-->
        
        <?php 
            function activateMenu($url)
            {
                return request()->is($url) ? 'active' : '' ;
            }
        ?>
        
        
        <nav class="navbar navbar-default" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Title</a>
                </div>
            
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav">
                        <li class=" {{ activateMenu('/') }}">
                            <a 
                                href="{{ route('home') }}">
                                Inicio
                            </a>
                        </li>
                        <li class=" {{ activateMenu('saludos/*') }}">
                            <a 
                                href="{{  route('saludos', 'YOMerengues') }}">
                                Saludo
                            </a> <!-- MAndando parametro opcional -->
                        </li>
                        <li class=" {{ activateMenu('mensajes/create') }}" >
                            <a 
                                href="{{  route('mensajes.create') }}">
                                Contacto
                            </a>
                        </li>
                    
                        
                        @if(auth()->check())
                            <li class=" {{ activateMenu('mensajes') }}">
                                <a   
                                    href="{{  route('mensajes.index') }}">
                                    Mensajes
                                </a>
                            </li>
                            
                            @if(auth()->user()->hasRoles(['admin','estudiante']))
                                <li class=" {{ activateMenu('usuarios*') }}">
                                    <a   
                                        href="{{  route('usuarios.index') }}">
                                        Usuarios
                                    </a>
                                </li>
                            @endif

                        @endif
                        
                    </ul>
                    
                    <ul class="nav navbar-nav navbar-right">
                        @if(auth()->guest())
                            <li class=" {{ activateMenu('login') }}">
                                <a   
                                    href="{{route('login')}}">
                                    login
                                </a>
                            </li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{auth()->user()->name}} <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/usuarios/{{ auth()->id() }}/edit">Mi cuenta</a></li>
                                    <li><a href="/logout">Cerrar sesion</a></li>
                                </ul>
                            </li>
                        @endif
                        
                        
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div>
        </nav>
    </header>
    
    <div class="container">
        @yield('content') <!-- section para que vaya el contenido de las otras plantillas-->

        <footer>
            Copiright {{date('Y')}}
        </footer>
    </div>

    <script src="/js/all.js"></script>
    
</body>
</html>

resources/views/saludo.blade.php
@extends('layout')

@section('content')
    <h1>Saludos para <?php echo $nombre ?></h1>
    <h1>Saludos para {{ $nombre }}</h1> <!-- Con Blade -->
    {!! $html !!}

    <ul>
        @foreach ($consolas as $consola)
            <li>{{ $consola }}</li>
        @endforeach
    </ul>

    <ul>
        @forelse ($consolas as $consola)
            <li>{{ $consola }}</li>
        @empty
            <p>No hay datos :(</p>
        @endforelse
    </ul>

    <!--Condicionales-->
    @if(count($consolas) === 1)
        <p>Tienes una consola</p>
    
    @elseif(count($consolas) > 1)
        <p>Tienes varias consolas</p>
    @else
        <p>No tienes consolas</p>

    @endif
    
@stop