routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Usando controladores
//Route::get('/', 'PagesController@home')->name('home')->middleware('example'); //Middleware

Route::get('/', 'PagesController@home')->name('home');

/*Route::get('contactos', 'PagesController@contactos')->name('contactos');

Route::post('contacto', 'PagesController@mensaje');

Route::get('contactame',[
    'as' => 'contactactamee', 
    'uses'=>'PagesController@contact'
    ]); //Otra forma de darle un Alias a un Controlador
*/

Route::get('saludos/{nombre?}', 'PagesController@saludos') //parametro opcional
                                ->name('saludos')
                                ->where('nombre', "[A-Za-z]+");


//USO de REST
/*Route::get('mensajes','MessagesController@index')->name('messages.index');
Route::get('mensajes/create','MessagesController@create')->name('messages.create');
Route::post('mensajes','MessagesController@store')->name('messages.store');
Route::get('mensajes/{id}','MessagesController@show')->name('messages.show');
Route::get('mensajes/{id}/edit','MessagesController@edit')->name('messages.edit');
Route::put('mensajes/{id}','MessagesController@update')->name('messages.update');
Route::delete('mensajes/{id}','MessagesController@destroy')->name('messages.destroy');*/




    //Ruta para crear un usuario de prueba

/*Route::get('test',function(){
    $user = new App\User;

    $user->name = 'Estudiante';
    $user->email = 'jorge3@gmail.com';
    $user->password = bcrypt('123123'); //Encriptamos la contraseña

    $user->save();

    return $user;

    $rol = new \App\Role;
    $rol->create([
        "nombre" => "admin",
        "description" => "Este rol tiene permisos de Administrador",
        "display_name" => "Administrador del sitio"
    ]);
    $rol2 = new \App\Role;
    $rol2->create([
        "nombre" => "mod",
        "description" => "Este rol tiene permisos de Moderador",
        "display_name" => "Moderador de comentarios"
    ]);

});*/

DB::listen(function($query){
    echo "<pre>{ $query->sql}</pre>";
});

Route::get('roles', function(){
    return \App\Role::with('user')->get();
});

//Reduciendo las rutas a una sola linea
Route::resource('mensajes','MessagesController');
Route::resource('usuarios','UsersController');


//Autenticacion

Route::get('login','Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout');
 

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','role',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function roles()
    {
        return $this->belongsToMany(Role::class,'assigned_roles'); //Obtiene todos los roles asociados al usuario
    }

    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = bcrypt($password);
    }


    public function hasRoles(array $roles)
    {
        //dd($this->roles); //Manda a llamar al metodo role()

        return $this->roles->pluck('nombre')->intersect($roles)->count();
        
        /*foreach ($roles as $role) 
        {
            
            foreach ($this->roles as $userRole) //
            {
                if ($userRole->nombre === $role){
    
                    return true;
                }
                
            }
        }
        return false;*/
    }

    public function isAdmin()
    {
        return $this->hasRoles(['admin']);
    }

    public function messages()
    {
        return $this->hasMany(Message::class);
    }

    public function note(){
        return $this->morphOne(Note::class,'notable');
    }

    public function tags(){
        return $this->morphToMany(Tag::class, 'taggable')->withTimestamps();
    }


}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Role;
use App\Http\Requests\UpdateRequest;
use App\Http\Requests\CreateUserRequest;

class UsersController extends Controller
{

    function __construct()
    {
        /*$this->middleware([
            'auth',
            'roles:admin',['except' => ['edit','update']] //Pase de paramatros
        ]); *///array de middlewares
        $this->middleware('auth',['except' => ['show']]);
        $this->middleware('roles:admin',['except' => ['edit','update','show']]); 
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::with('roles','note','tags')->get();

        return view('users.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::pluck('display_name', 'id');//Valor => llave
        return view('users.create',compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateUserRequest $request)
    {
        $user = User::create($request->all());
        $user->roles()->attach($request->roles);

        return redirect()->route('usuarios.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);

        return view('users.show', compact('user'));        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //dd(auth()->user());
        $user = User::findOrFail($id);

        $this->authorize('edit',$user); //Hacemos la llamada a la politica creada,
                                 //Se pasa el nombre de la funcion creada en la Politica y el usuario

        $roles = Role::pluck('display_name', 'id');//Valor => llave

        return view('users.edit', compact('user','roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, $id)
    {

        $user = User::findOrFail($id);

        $this->authorize('update',$user);
        
        $user->update($request->only('name','email'));

        $user->roles()->sync($request->roles); //INsercion ManyToMany

        return back()->with('info', 'Usuario Actualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);

        $this->authorize('destroy',$user);

        $user->delete();

        return back();
    }
}

resources/views/users/create.blade.php
@extends('layout')

@section('content')
    <h1>Crear nuevo Usuario</h1>

    <form action="{{route('usuarios.store')}}" method="POST">
        
        @include('users.form',['user'=> new \App\User])       
                
        <input class="btn btn-primary" type="submit" value="Guardar">
    </form>

@stop

resources/views/users/edit.blade.php
@extends('layout')

@section('content')
    <h1>Editar Contenido</h1>

    @if(session()->has('info'))
        <div class="alert alert-success">{{session('info')}}</div>
    @endif

    <form action="{{route('usuarios.update',$user->id)}}" method="POST">
        {!! method_field('PUT') !!} <!--para poder hacer uso de PUT-->
        
        @include('users.form')       
                
        <input class="btn btn-primary" type="submit" value="Enviar">
    </form>
@stop

resources/views/users/form.blade.php
{!! csrf_field() !!}
<p><label for="nombre">
    Nombre:
    <input  class="form-control" type="text" name="name" value="{{ $user->name or old('name') }}">
    {!! $errors->first('name','<span class="error">:message</span>') !!}
</label></p>
<p><label for="email">
    Email:
    <input  class="form-control" type="text" name="email" value="{{$user->email or old('email')}}">
    {!! $errors->first('email','<span class="error">:message</span>') !!}
</label></p>

@unless ($user->id)
    <p><label for="password">
    Password:
    <input  class="form-control" type="password" name="password" >
    {!! $errors->first('password','<span class="error">:message</span>') !!}
    </label></p>

    <p><label for="password_confirmation">
    Confirmar Password:
    <input  class="form-control" type="password" name="password_confirmation" >
    {!! $errors->first('password_confirmation','<span class="error">:message</span>') !!}
    </label></p>
@endunless

<div class="checkbox">
    @foreach($roles as $id => $name)
        <label>
            <input 
                type="checkbox" 
                value="{{$id}}" 
                {{$user->roles->pluck('id')->contains($id) ? 'checked' : ''}}
                name="roles[]"
            >
            {{$name}}
        </label>
    @endforeach
    
</div>
{!! $errors->first('roles','<span class="error">:message</span>') !!}
<hr>

resources/views/users/index.blade.php
@extends('layout')

@section('content')
    <h1>Usuarios</h1>
    
    <a class="btn btn-success pull-right" href="{{route('usuarios.create')}}">Crear nuevo Usuario</a>
    
    <table class="table">
        <thead>                
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Email</th>
                <th>Role</th>
                <th>Notas</th>
                <th>Tags</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach($users as $user)
                <tr>
                    <td> {{$user->id}} </td>
                    <td>
                        <a href="{{route('usuarios.show', $user->id )}}"> 
                             {{$user->name}} 
                        </a>
                    </td>
                    <td> {{$user->email}} </td>
                    <td>
                        {{$user->roles->pluck('display_name')->implode(', ')}}
                    </td>
                    <td>{{ $user->note ? $user->note->body : "" }}</td>
                    <td>{{ $user->tags ? $user->tags->pluck('name')->implode(', ') : "" }}</td>
                    <td>
                        <a class="btn btn-info btn-xs" href="{{route('usuarios.edit',$user->id)}}">
                            Editar
                        </a>
                        <form style="display:inline" method="POST" action="{{route('usuarios.destroy',$user->id)}}">
                            {!! csrf_field() !!}
                            {!! method_field('DELETE') !!}
                            <button class="btn btn-danger btn-xs" type="submit">Eliminar</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@stop

resources/views/users/show.blade.php
@extends('layout')

@section('content')
    <h1>{{ $user->name }}</h1>
    <table class="table">
        <tr>
            <th>Nombre:</th>
            <th>{{$user->name}}</th>
        </tr>
        <tr>
            <th>Email:</th>
            <th>{{$user->email}}</th>
        </tr>
        <tr>
            <th>Roles</th>
            <td>
                @foreach ($user->roles as $role)
                    {{$role->display_name}} 
                @endforeach 
            </td>
        </tr>
    </table>

    @can('edit',$user)
        <a href="{{route('usuarios.edit',$user->id)}}" class="btn btn-info">Editar</a>
    @endcan

    @can('destroy',$user)
        <form style="display:inline" method="POST" action="{{route('usuarios.destroy',$user->id)}}">
            {!! csrf_field() !!}
            {!! method_field('DELETE') !!}
            <button class="btn btn-danger" type="submit">Eliminar</button>
        </form>
    @endcan
@stop