routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Usando controladores
//Route::get('/', 'PagesController@home')->name('home')->middleware('example'); //Middleware

Route::get('/', 'PagesController@home')->name('home');

/*Route::get('contactos', 'PagesController@contactos')->name('contactos');

Route::post('contacto', 'PagesController@mensaje');

Route::get('contactame',[
    'as' => 'contactactamee', 
    'uses'=>'PagesController@contact'
    ]); //Otra forma de darle un Alias a un Controlador
*/

Route::get('saludos/{nombre?}', 'PagesController@saludos') //parametro opcional
                                ->name('saludos')
                                ->where('nombre', "[A-Za-z]+");


//USO de REST
/*Route::get('mensajes','MessagesController@index')->name('messages.index');
Route::get('mensajes/create','MessagesController@create')->name('messages.create');
Route::post('mensajes','MessagesController@store')->name('messages.store');
Route::get('mensajes/{id}','MessagesController@show')->name('messages.show');
Route::get('mensajes/{id}/edit','MessagesController@edit')->name('messages.edit');
Route::put('mensajes/{id}','MessagesController@update')->name('messages.update');
Route::delete('mensajes/{id}','MessagesController@destroy')->name('messages.destroy');*/




    //Ruta para crear un usuario de prueba

/*Route::get('test',function(){
    $user = new App\User;

    $user->name = 'Estudiante';
    $user->email = 'jorge3@gmail.com';
    $user->password = bcrypt('123123'); //Encriptamos la contraseña

    $user->save();

    return $user;

    $rol = new \App\Role;
    $rol->create([
        "nombre" => "admin",
        "description" => "Este rol tiene permisos de Administrador",
        "display_name" => "Administrador del sitio"
    ]);
    $rol2 = new \App\Role;
    $rol2->create([
        "nombre" => "mod",
        "description" => "Este rol tiene permisos de Moderador",
        "display_name" => "Moderador de comentarios"
    ]);

});*/

DB::listen(function($query){
    echo "<pre>{ $query->sql}</pre>";
});

Route::get('roles', function(){
    return \App\Role::with('user')->get();
});

//Reduciendo las rutas a una sola linea
Route::resource('mensajes','MessagesController');
Route::resource('usuarios','UsersController');


//Autenticacion

Route::get('login','Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout');
 

app/Message.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Message extends Model
{
    protected $table = "messages"; //Asignarle una tabla diferente al nombre que tiene el modelo
    protected $fillable = ['nombre','email','mensaje']; //Asignar que campos puede insertar


    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function note(){
        return $this->morphOne(Note::class, 'notable');
    }

    public function tags(){
        return $this->morphToMany(Tag::class, 'taggable')->withTimestamps();
    }


}

app/Http/Controllers/MessagesController.php
<?php

namespace App\Http\Controllers;

use DB;
use Mail;
use App\User;
use App\Message;
use Carbon\Carbon;

use Illuminate\Http\Request;
use App\Events\MessageWasReceived;
use Illuminate\Support\Facades\Cache;

class MessagesController extends Controller
{

    function __construct()
    {
        $this->middleware('auth',['except' =>['create','store']]); //Middleware para evitar acceder a rutas mediante la URL
    }


    public function index()
    {
        //$messages =  DB::table('messages')->get(); //Query Builder
        $key = "messages.page". request('page',1); //para la paginacion
        
        $messages = Cache::rememberForever($key, function () {
            return Message::with('user','note','tags')->paginate(2);
        });

        // if(Cache::has('messages.all')){
            // $messages = Cache::get('messages.all');
        // }

        // else {
        //     $messages = Message::with('user','note','tags')->paginate(2); //Eloquent
        //     Cache::put('messages.all', $messages, 1);
        // }
         
        
        return view(
            'messages.index',  //Retornamos la vista que se encuentra en views/messages/index.blade.php
            compact('messages') //Retornamos la variable $messages
        );
    }

    public function create()
    {
        return view('messages.create'); //Retornamos la vista que se encuentra en views/messages/create.blade.php
    }

    public function store(Request $request)
    {
        //Guradar el mensaje 
        /*DB::table('messages')->insert([
            "nombre" => $request->input('nombre'),
            "email" => $request->input('email'),
            "mensaje" => $request->input('mensaje'),
            "created_at" => Carbon::now(),
            "updated_at" => Carbon::now(),
        ]);*/  //Query Builder


        //Primera forma de insertar un nuevo registro
        /*$message = new Message;
        $message->nombre = $request->input('nombre');
        $message->email = $request->input('email');
        $message->mensaje = $request->input('mensaje');
 
        $message->save();*/

        //Segunda Forma de insertar nuevo registro
        
        //Tercera forma de insertar un nuevo registro
        /*Message::create([
            "nombre" => $request->input('nombre'),
            "email" => $request->input('email'),
            "mensaje" => $request->input('mensaje')
            ]);*/
        

        $message = new Message;
        if(auth()->check())
        {
            $message->nombre = auth()->user()->name; 
            $message->email =  auth()->user()->email;
        }
        else {
            $message->nombre = $request->input('nombre') ? $request->input('nombre') : '';
            $message->email = $request->input('email') ? $request->input('email') : '';
        }
        
        $message->mensaje = $request->input('mensaje');

        
        $message->save();
 
        if(auth()->check())
        {
            auth()->user()->messages()->save($message);
        }
        
        event(new MessageWasReceived($message));
        /*auth()->user()->messages()->create($request->all()); //Solo funciona si lo hacen usuarios autenticados

        
        $message = new Message;
        $message->nombre = '';
        $message->email = '';
        $message->mensaje = $request->input('mensaje');

        $message->user_id = auth()->user()->id;

        $message->save();*/

        Cache::flush();
        //Redireccionar
        return redirect()->route('mensajes.create')->with('keyMensaje', 'Hemos recibido tu mensaje');
    }

    public function show($id)
    {
        //$message = DB::table('messages')->where('id',$id)->first(); //Query Builder

        $message = Cache::remember('message'.$id, 5,function () use ($id) {
            return Message::findOrFail($id); //Eloquent
        });


        return view(
            'messages.show',
            compact('message')
        );
    }

    public function edit($id)
    {
        //$message = DB::table('messages')->where('id',$id)->first(); //Query Builder

        $message = Cache::remember('message'.$id, 5,function () use ($id) {
            return Message::findOrFail($id); //Eloquent
        });
        
        return view(
            'messages.edit',
            compact('message')
        );
    }

    public function update(Request $request, $id)
    {
        //Actualizamos
        /*DB::table('messages')->where('id',$id)->update([
            "nombre" => $request->input('nombre'),
            "email" => $request->input('email'),
            "mensaje" => $request->input('mensaje'),
            "updated_at" => Carbon::now(),
        ]);*/ //Query Builder
        

        /*$message = Message::findOrFail($id); //Buscamos el registro
        $message->update($request->all()); //Editamos el registro encontrado anteriormente
        */

        //En una sola linea
        Message::findOrFail($id)->update($request->all());
        Cache::flush();
        //Redireccionamos
        return redirect()->route('mensajes.index');
    }

    public function destroy($id)
    {
        //Eliminadr mensaje
        //DB::table('messages')->where('id',$id)->delete(); //Query Builder

        Message::findOrFail($id)->delete(); //Eloquent
        Cache::flush();
        //Redireccionar
        return redirect()->route('mensajes.index');
    }
}

resources/views/messages/create.blade.php
@extends('layout')

@section('content')
    <h1>CONTACTOS</h1>
    <h2>Escribenos</h2>
    @if(session()->has('keyMensaje'))
    
        <h3>{{ session('keyMensaje')}}</h3>
    
    @else
    <form action="{{route('mensajes.store')}}" method="POST">
        @include('messages.form',[
            'message' => new App\Message,
            'showFields' => auth()->guest(),
        ])
    </form>
    <hr>
    @endif
    
@stop

resources/views/messages/edit.blade.php
@extends('layout')

@section('content')
    <h1>Editar Mensaje</h1>
    <form action="{{route('mensajes.update',$message->id)}}" method="POST">
        {!! method_field('PUT') !!} <!--para poder hacer uso de PUT-->
        {!! csrf_field() !!}
        @include('messages.form',[
            'btnText' => 'Actualizar',
            'showFields' => ! $message->user_id
        ])
    </form>
@stop

resources/views/messages/form.blade.php
@if( $showFields)
    <p><label for="nombre">
        Nombre:
        <input class="form-control" type="text" name="nombre" value="{{ $message->nombre or old('nombre') }}">
        {!! $errors->first('nombre','<span class="error">:message</span>') !!}
    </label></p>
    <p><label for="email">
        Email:
        <input class="form-control" type="text" name="email" value="{{ $message->email or old('email')}}">
        {!! $errors->first('email','<span class="error">:message</span>') !!}
    </label></p>

@endif
<p><label for="mensaje">
    Mensaje:
    <textarea class="form-control" name="mensaje"> {{$message->mensaje or old('mensaje')}}</textarea>
    {!! $errors->first('mensaje','<span class="error">:message</span>') !!}
</label></p>

<input class="btn btn-primary" type="submit" value="{{ isset($btnText) ? $btnText : 'Guardar'}}">

resources/views/messages/index.blade.php
@extends('layout')

@section('content')
    <h1>Todos los mensajes</h1>
    <table class="table">
        <thead>                
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Email</th>
                <th>Mensaje</th>
                <th>Notas</th>
                <th>Tags</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach($messages as $message)
                <tr>
                    <td> {{$message->id}} </td>
                    
                    @if($message->user_id)
                        <td>
                            <a href="{{route('usuarios.show',$message->user_id)}}">
                                {{$message->user->name}}
                            </a>
                        </td>
                        <td>{{$message->user->email}}</td>
                    @else
                        <td> {{$message->nombre}} </td>
                        <td> {{$message->email}} </td>
                    @endif
                    <td> 
                        <a href="{{route('mensajes.show', $message->id )}}"> 
                            {{$message->mensaje}} 
                        </a>
                        
                    </td>
                    <td>{{ $message->note ? $message->note->body : "" }}</td>
                    <td>{{ $message->tags ? $message->tags->pluck('name')->implode(', ') : "" }}</td>
                    <td>
                        <a class="btn btn-info btn-xs" href="{{route('mensajes.edit',$message->id)}}">
                            Editar
                        </a>
                        <form style="display:inline" method="POST" action="{{route('mensajes.destroy',$message->id)}}">
                            {!! csrf_field() !!}
                            {!! method_field('DELETE') !!}
                            <button class="btn btn-danger btn-xs" type="submit">Eliminar</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    {!! $messages
        ->fragment('hash') //#hash
        ->appends(request()->query())//Parametros &osorted=asc
        ->render("pagination::simple-default") !!}

    {!! $messages
        ->fragment('hash') //#hash
        ->appends(request()->query())//Parametros &osorted=asc
        ->links("pagination::default") !!}
@stop

resources/views/messages/show.blade.php
@extends('layout')

@section('content')
    <h1>Mensaje</h1>
    <p>Enviado por {{$message->nombre}} - {{$message->email}}</p>
    <p>{{$message->mensaje}} </p>
    
@stop